<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="home.aspx.cs" Inherits="PlacementCell.home" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <%--    <style>
        body {
            height: 100%;
            /*background-image: url('http://localhost:50312/images/Thumbnails.jpg');*/
        }

        iframe {
            display: block; /* iframes are inline by default */
            background: #000;
            border: none; /* Reset default border */
            height: 100vh; /* Viewport-relative units */
            width: 100vw;
        }

        .bgc {
            height: 100%;
            width: 100%;
        }
    </style>--%>
   <!-- Generated by Jssor Slider Maker Online. -->
    <!-- This demo works with jquery library -->
   <!-- Generated by Jssor Slider Maker Online. -->
    <!-- This demo works with jquery library -->

    <script type="text/javascript" src="js/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="js/jssor.slider.mini.js"></script>
    <!-- use jssor.slider.debug.js instead for debug -->
    <script>
        jQuery(document).ready(function ($) {
            
            var jssor_1_SlideshowTransitions = [
              {$Duration:1200,$Opacity:2}
            ];
            
            var jssor_1_SlideoTransitions = [
              [{b:0,d:1000,y:-440,e:{y:27}}],
              [{b:0,d:1000,y:185},{b:1000,d:500,o:-1},{b:1500,d:500,o:1}],
              [{ b: -1, d: 1, o: -1 }, { b: 0, d: 1000, o: 1, e: { o: 5 } }],
              [{ b: 0, d: 1000, y: -440, e: { y: 27 } }]
            ];
            
            var jssor_1_options = {
              $AutoPlay: true,
              $Idle: 2000,
              $SlideshowOptions: {
                $Class: $JssorSlideshowRunner$,
                $Transitions: jssor_1_SlideshowTransitions,
                $TransitionsOrder: 1
              },
              $CaptionSliderOptions: {
                $Class: $JssorCaptionSlideo$,
                $Transitions: jssor_1_SlideoTransitions
              },
              $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
              },
              $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$
              }
            };
            
            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);
            
            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizing
            function ScaleSlider() {
                var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
                if (refSize) {
                    jssor_1_slider.$ScaleWidth(refSize);
                }
                else {
                    window.setTimeout(ScaleSlider, 30);
                }
            }
            ScaleSlider();
            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
    </script>

    <style>
        
        /* jssor slider bullet navigator skin 21 css */
        /*
        .jssorb21 div           (normal)
        .jssorb21 div:hover     (normal mouseover)
        .jssorb21 .av           (active)
        .jssorb21 .av:hover     (active mouseover)
        .jssorb21 .dn           (mousedown)
        */
        .jssorb21 {
            position: absolute;
        }
        .jssorb21 div, .jssorb21 div:hover, .jssorb21 .av {
            position: absolute;
            /* size of bullet elment */
            width: 19px;
            height: 19px;
            text-align: center;
            line-height: 19px;
            color: white;
            font-size: 12px;
            background: url('img/b21.png') no-repeat;
            overflow: hidden;
            cursor: pointer;
        }
        .jssorb21 div { background-position: -5px -5px; }
        .jssorb21 div:hover, .jssorb21 .av:hover { background-position: -35px -5px; }
        .jssorb21 .av { background-position: -65px -5px; }
        .jssorb21 .dn, .jssorb21 .dn:hover { background-position: -95px -5px; }

        /* jssor slider arrow navigator skin 14 css */
        /*
        .jssora14l                  (normal)
        .jssora14r                  (normal)
        .jssora14l:hover            (normal mouseover)
        .jssora14r:hover            (normal mouseover)
        .jssora14l.jssora14ldn      (mousedown)
        .jssora14r.jssora14rdn      (mousedown)
        */
        .jssora14l, .jssora14r {
            display: block;
            position: absolute;
            /* size of arrow element */
            width: 30px;
            height: 50px;
            cursor: pointer;
            background: url('img/a14.png') no-repeat;
            overflow: hidden;
        }
        .jssora14l { background-position: -15px -35px; }
        .jssora14r { background-position: -75px -35px; }
        .jssora14l:hover { background-position: -135px -35px; }
        .jssora14r:hover { background-position: -195px -35px; }
        .jssora14l.jssora14ldn { background-position: -255px -35px; }
        .jssora14r.jssora14rdn { background-position: -315px -35px; }
    </style>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="main_content" runat="server">
    <%--<div style="height:100vh; background-image: url('images/Thumbnails.jpg'); background-repeat:no-repeat; background-size:100vw 100vh">
        <img src="images/somaiya_logo.jpg" />
            <h4>S.K Somaiya Degree College Of Arts, Science And Commerce </h4>
        <br />
        <br />
        <br />
    </div>--%>
 
    <div id="jssor_1" style="position: relative; top: 0px; left: 0px; width: 900px; height: 300px; overflow: hidden; visibility: hidden;">
        <!-- Loading Screen -->
        <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
            <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
            <div style="position:absolute;display:block;background:url('img/loading2.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
        </div>
        <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 900px; height: 300px; overflow: hidden;">
            <div data-p="150.00" style="display: none;">
                <img data-u="image" src="img/880-sk-somaiyacollege-vidyavihar-mumbai.jpg" />
                <div data-u="caption" data-t="0" style="position: absolute; top: 520px; left: 20px; width: 350px; height: 30px; background-color: rgba(235,81,0,0.5); font-size: 20px; color: #ffffff; line-height: 30px; text-align: center;">Impart knowledge through value based education.</div>
            </div>
            <div data-p="150.00" style="display: none;">
                <img data-u="image" src="img/floor.jpg" />
                <div data-u="caption" data-t="1" style="position: absolute; top: -50px; left: 125px; width: 350px; height: 30px; background-color: rgba(235,81,0,0.5); font-size: 20px; color: #ffffff; line-height: 30px; text-align: center;">Promote and facilitate quality research amongst faculty and students.</div>
            </div>
            <div data-p="150.00" style="display: none;">
                <img data-u="image" src="img/lobby.jpg" />
                <div data-u="caption" data-t="2" style="position: absolute; top: 250px; left: 500px; width: 350px; height: 30px; background-color: rgba(235,81,0,0.5); font-size: 20px; color: #ffffff; line-height: 30px; text-align: center;">Provide a learning continuum and make pedagogy more student centric.</div>
            </div>
             <div data-p="150.00" style="display: none;">
                <img data-u="image" src="img/floor.jpg" />
                <div data-u="caption" data-t="1" style="position: absolute; top: -50px; left: 125px; width: 350px; height: 30px; background-color: rgba(235,81,0,0.5); font-size: 20px; color: #ffffff; line-height: 30px; text-align: center;"></div>
            </div>
        </div>
        <!-- Bullet Navigator -->
        <div data-u="navigator" class="jssorb21" style="bottom:16px;right:16px;" data-autocenter="1">
            <!-- bullet navigator item prototype -->
            <div data-u="prototype" style="width:19px;height:19px;"></div>
        </div>
        <!-- Arrow Navigator -->
        <span data-u="arrowleft" class="jssora14l" style="top:0px;left:8px;width:30px;height:50px;" data-autocenter="2"></span>
        <span data-u="arrowright" class="jssora14r" style="top:0px;right:8px;width:30px;height:50px;" data-autocenter="2"></span>
        <a href="http://www.jssor.com" style="display:none">Slideshow Maker</a>
    </div>




</asp:Content>
